name = "LombScargle"
uuid = "fc60dff9-86e7-5f2f-a8a0-edeadbb75bd9"
authors = ["Mos√® Giordano <mose@gnu.org>"]
version = "1.0.1"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
FFTW = "0.2.3, 0.3, 1"
Measurements = "1, 2"
SpecialFunctions = "0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 1.0"
StableRNGs = "0.1, 1"
julia = "1"

[extras]
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["StableRNGs", "Test"]
